### ISSUE TITLE
Description of parameters

### ISSUE THREAD

**Issue by slawekzz** [dpoulson/EPSolar#3]
Hello
At the outset, I would like to congratulate the project. Very good. I used it to read data from the EPsolar LS1024B. In the description you posted you described several values ​​that are passed by MQTT. Some other ones are sent to server. Can you document the others?
EPSolar/1/battChargeCurrent
EPSolar/1/batt_boostrecon
EPSolar/1/batt_boostvolt
EPSolar/1/batt_cap
EPSolar/1/batt_chargelimit
EPSolar/1/batt_equalvolt
EPSolar/1/batt_floatvolt
EPSolar/1/batt_highdisc
EPSolar/1/batt_lowvoltdisc
EPSolar/1/batt_lowvoltrecon
EPSolar/1/batt_overvoltrecon
EPSolar/1/batt_undervoltrecon
EPSolar/1/batt_undervoltwarn
EPSolar/1/bremaining
EPSolar/1/btemp
EPSolar/1/bvoltage
EPSolar/1/ctemp
EPSolar/1/lcurrent
EPSolar/1/loop1
EPSolar/1/lpower
EPSolar/1/pvcurrent
EPSolar/1/pvpower
EPSolar/1/pvvoltage/ESP_Easy/status
EPSolar/1/battChargeCurrent
EPSolar/1/batt_boostrecon
EPSolar/1/batt_boostvolt
EPSolar/1/batt_cap
EPSolar/1/batt_chargelimit
EPSolar/1/batt_equalvolt
EPSolar/1/batt_floatvolt
EPSolar/1/batt_highdisc
EPSolar/1/batt_lowvoltdisc
EPSolar/1/batt_lowvoltrecon
EPSolar/1/batt_overvoltrecon
EPSolar/1/batt_undervoltrecon
EPSolar/1/batt_undervoltwarn
EPSolar/1/bremaining
EPSolar/1/btemp
EPSolar/1/bvoltage
EPSolar/1/ctemp
EPSolar/1/lcurrent
EPSolar/1/loop1
EPSolar/1/lpower
EPSolar/1/pvcurrent
EPSolar/1/pvpower
EPSolar/1/pvvoltage

**Comment by oori** [comment]
You can find the description (and more) here:
http://steinsland.net/wp/wp-content/uploads/2017/10/BSeriesControllerProtocolv2.4.pdf
