### ISSUE TITLE
cant find the right libaries

### ISSUE THREAD

**Issue by kitt2011** [dpoulson/EPSolar#6]
Hello,

big thanks for your work. I cant compile and upload the file because i dont find all libaries. Any help?
Thank you!

**Comment by kitt2011** [comment]
In file included from C:\Users\Fabian\Documents\Arduino\libraries\LeifHomieLib-master\src/LeifHomieLib.h:3,
                 from C:\Users\Fabian\Desktop\EPSolar-master\EPSolar\EPSolar.ino:26:
C:\Users\Fabian\Documents\Arduino\libraries\LeifHomieLib-master\src/HomieDevice.h:8:10: fatal error: AsyncMqttClient.h: No such file or directory
    8 | #include "AsyncMqttClient.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Mehrere Bibliotheken wurden für "SimpleTimer.h" gefunden
 Benutzt: C:\Users\Fabian\Documents\Arduino\libraries\SimpleTimer-master
 Nicht benutzt: C:\Users\Fabian\Documents\Arduino\libraries\SimpleTimer-1.0.0
exit status 1
Fehler beim Kompilieren für das Board NodeMCU 1.0 (ESP-12E Module).


need the right leifhomielib

**Comment by TerryFrench** [comment]
https://github.com/marvinroger/async-mqtt-client
is likely what you need
